In [7]:
import pandas as pd

In [8]:
patientHeartRate = pd.read_csv("https://raw.githubusercontent.com/huynhhoc/DataAnalystDeepLearning/main/Data/patient_heart_rate.csv")
patientHeartRate.head(5)

     1    Mickéy Mousé    56       70kgs  72  69  71   -  -.1 -.2
0  2.0     Donald Duck  34.0   154.89lbs   -   -   -  85   84  76
1  3.0      Mini Mouse  16.0         NaN   -   -   -  65   69  72
2  4.0  Scrooge McDuck   NaN       78kgs  78  79  72   -    -   -
3  5.0    Pink Panther  54.0  198.658lbs   -   -   -  69  NaN  75
4  6.0     Huey McDuck  52.0      189lbs   -   -   -  68   75  72

In [9]:
#Van de 1
columnNames = ["ID", "Name", "Age", "Weight", "m0006", "m0612", "m1218", "f0006", "f0612", "f1218"]
patientHeartRate = pd.read_csv("https://raw.githubusercontent.com/huynhhoc/DataAnalystDeepLearning/main/Data/patient_heart_rate.csv", names=columnNames)
patientHeartRate.head(5)

    ID            Name   Age      Weight m0006 m0612 m1218 f0006 f0612 f1218
0  1.0    Mickéy Mousé  56.0       70kgs    72    69    71     -     -     -
1  2.0     Donald Duck  34.0   154.89lbs     -     -     -    85    84    76
2  3.0      Mini Mouse  16.0         NaN     -     -     -    65    69    72
3  4.0  Scrooge McDuck   NaN       78kgs    78    79    72     -     -     -
4  5.0    Pink Panther  54.0  198.658lbs     -     -     -    69   NaN    75

In [10]:
#Vam de 2
patientHeartRate[["FirstName", "LastName"]] = patientHeartRate["Name"].str.split(expand=True)
patientHeartRate = patientHeartRate.drop("Name", axis=1)
patientHeartRate.head(5)

,ID,Age,Weight,m0006,m0612,m1218,f0006,f0612,f1218,FirstName,LastName
0,1.0,56.0,70kgs,72,69,71,-,-,-,Mickéy,Mousé
1,2.0,34.0,154.89lbs,-,-,-,85,84,76,Donald,Duck
2,3.0,16.0,NaN,-,-,-,65,69,72,Mini,Mouse
3,4.0,NaN,78kgs,78,79,72,-,-,-,Scrooge,McDuck
4,5.0,54.0,198.658lbs,-,-,-,69,NaN,75,Pink,Panther

In [95]:
#Van de 3
weight = patientHeartRate["Weight"]
for i in range (0, len(weight)):
    x = str(weight[i])
    if "lbs" in x[-3:]:
        x = x[:-3]
        floatX = float(x)
        y = int(floatX / 2.2)
        y = str(y) + "kgs"
        weight[i] = y

print(patientHeartRate)

      ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 FirstName LastName
0    1.0  56.0  70kgs    72    69    71    -     -     -    Mickéy    Mousé
1    2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -   65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72    -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -   69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -   68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -   71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75    -     -     -    Scööpy      Doo
8    NaN   NaN    NaN   NaN   NaN   NaN  NaN   NaN   NaN       NaN      NaN
9    NaN   NaN    NaN   NaN   NaN   NaN  NaN   NaN   NaN       NaN      NaN
10   9.0  52.0  85kgs     -     -     -   68    75    72      Huey   McDuck
11  10.0  12.0  45kgs     -     -     -   92    95    87     Louie   McDuck
12  11.0   NaN  60kgs    78    75    72    -     -     -     Henry      Nam
13  12.0  34.0    NaN    65    67    55    -     -     -    Michel     Long
14  13.0   NaN    NaN     -     -     -   68    72    70      Tana    Ricky
15  14.0   NaN    NaN   NaN   NaN   NaN  NaN   NaN   NaN  UniLever     None
16  15.0  52.0  81kgs     -     -     -   68    75    72       NaN      NaN

C:\Users\US\AppData\Local\Temp\ipykernel_8264\2040165767.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weight[i] = y

In [96]:
#Van de 4
patientHeartRate.dropna(how="all", inplace=True)
print(patientHeartRate)

      ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 FirstName LastName
0    1.0  56.0  70kgs    72    69    71    -     -     -    Mickéy    Mousé
1    2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -   65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72    -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -   69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -   68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -   71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75    -     -     -    Scööpy      Doo
10   9.0  52.0  85kgs     -     -     -   68    75    72      Huey   McDuck
11  10.0  12.0  45kgs     -     -     -   92    95    87     Louie   McDuck
12  11.0   NaN  60kgs    78    75    72    -     -     -     Henry      Nam
13  12.0  34.0    NaN    65    67    55    -     -     -    Michel     Long
14  13.0   NaN    NaN     -     -     -   68    72    70      Tana    Ricky
15  14.0   NaN    NaN   NaN   NaN   NaN  NaN   NaN   NaN  UniLever     None
16  15.0  52.0  81kgs     -     -     -   68    75    72       NaN      NaN

In [97]:
#Van de 5
patientHeartRate = patientHeartRate.drop_duplicates(subset=["FirstName", "LastName", "Age", "Weight"])
print(patientHeartRate)

      ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 FirstName LastName
0    1.0  56.0  70kgs    72    69    71    -     -     -    Mickéy    Mousé
1    2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -   65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72    -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -   69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -   68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -   71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75    -     -     -    Scööpy      Doo
11  10.0  12.0  45kgs     -     -     -   92    95    87     Louie   McDuck
12  11.0   NaN  60kgs    78    75    72    -     -     -     Henry      Nam
13  12.0  34.0    NaN    65    67    55    -     -     -    Michel     Long
14  13.0   NaN    NaN     -     -     -   68    72    70      Tana    Ricky
15  14.0   NaN    NaN   NaN   NaN   NaN  NaN   NaN   NaN  UniLever     None
16  15.0  52.0  81kgs     -     -     -   68    75    72       NaN      NaN

In [98]:
#van de 6
patientHeartRate.FirstName.replace({r'[^\x00-\x7F]+':''}, regex=True, inplace=True)
patientHeartRate.LastName.replace({r'[^\x00-\x7F]+':''}, regex=True, inplace=True)
print(patientHeartRate)

      ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 FirstName LastName
0    1.0  56.0  70kgs    72    69    71    -     -     -     Micky     Mous
1    2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -   65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72    -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -   69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -   68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -   71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75    -     -     -      Scpy      Doo
11  10.0  12.0  45kgs     -     -     -   92    95    87     Louie   McDuck
12  11.0   NaN  60kgs    78    75    72    -     -     -     Henry      Nam
13  12.0  34.0    NaN    65    67    55    -     -     -    Michel     Long
14  13.0   NaN    NaN     -     -     -   68    72    70      Tana    Ricky
15  14.0   NaN    NaN   NaN   NaN   NaN  NaN   NaN   NaN  UniLever     None
16  15.0  52.0  81kgs     -     -     -   68    75    72       NaN      NaN

In [48]:
#van de 7
#a
patientHeartRate.dropna(how="any", inplace=True)
print(patientHeartRate)

      ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 FirstName LastName
0    1.0  56.0  70kgs    72    69    71    -     -     -     Micky     Mous
1    2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
5    6.0  52.0  85kgs     -     -     -   68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -   71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75    -     -     -      Scpy      Doo
11  10.0  12.0  45kgs     -     -     -   92    95    87     Louie   McDuck

In [85]:
#van de 7
#b
patientHeartRate = patientHeartRate.fillna(0)

print(patientHeartRate)

AttributeError: 'NoneType' object has no attribute 'fillna'

In [92]:
#van de 7
#c

patientHeartRate.fillna(patientHeartRate.mean(), inplace=True)
print(patientHeartRate)

      ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 FirstName LastName
0    1.0  56.0  70kgs    72    69    71    -     -     -     Micky     Mous
1    2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -   65    69    72      Mini    Mouse
3    4.0  36.1  78kgs    78    79    72    -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -   69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -   68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -   71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75    -     -     -      Scpy      Doo
11  10.0  12.0  45kgs     -     -     -   92    95    87     Louie   McDuck
12  11.0  36.1  60kgs    78    75    72    -     -     -     Henry      Nam
13  12.0  34.0    NaN    65    67    55    -     -     -    Michel     Long
14  13.0  36.1    NaN     -     -     -   68    72    70      Tana    Ricky
15  14.0  36.1    NaN   NaN   NaN   NaN  NaN   NaN   NaN  UniLever     None
16  15.0  52.0  81kgs     -     -     -   68    75    72       NaN      NaN

In [100]:
#van de 7
#d
patientHeartRate = patientHeartRate.fillna(patientHeartRate.mode().iloc[0])
print(patientHeartRate)

      ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 FirstName LastName
0    1.0  56.0  70kgs    72    69    71    -     -     -     Micky     Mous
1    2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
2    3.0  16.0  70kgs     -     -     -   65    69    72      Mini    Mouse
3    4.0  34.0  78kgs    78    79    72    -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -   69     -    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -   68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -   71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75    -     -     -      Scpy      Doo
11  10.0  12.0  45kgs     -     -     -   92    95    87     Louie   McDuck
12  11.0  34.0  60kgs    78    75    72    -     -     -     Henry      Nam
13  12.0  34.0  70kgs    65    67    55    -     -     -    Michel     Long
14  13.0  34.0  70kgs     -     -     -   68    72    70      Tana    Ricky
15  14.0  34.0  70kgs     -     -     -    -     -     -  UniLever   McDuck
16  15.0  52.0  81kgs     -     -     -   68    75    72     Dewey   McDuck

In [11]:
#van de 8
patientHeartRate = pd.melt(patientHeartRate, id_vars=["ID", "Age", "Weight", "FirstName", "LastName"], value_name="PulseRate", var_name="sex_and_time").sort_values(["ID", "Age", "Weight", "FirstName", "LastName"])

tmpDf = patientHeartRate["sex_and_time"].str.extract(r"(\D)(\d+)(\d{2})", expand=True)

tmpDf.columns = ["Sex", "hours_lower", "hours_upper"]

tmpDf["Time"] = tmpDf["hours_lower"] + "-" + tmpDf["hours_upper"]

patientHeartRate = pd.concat([patientHeartRate, tmpDf], axis=1)

patientHeartRate = patientHeartRate.drop(["sex_and_time", "hours_lower", "hours_upper"], axis=1)
patientHeartRate = patientHeartRate.dropna()
patientHeartRate.to_csv("outputcleanup.csv", index=False)
print(patientHeartRate)

      ID   Age      Weight FirstName LastName PulseRate Sex   Time
0    1.0  56.0       70kgs    Mickéy    Mousé        72   m  00-06
17   1.0  56.0       70kgs    Mickéy    Mousé        69   m  06-12
34   1.0  56.0       70kgs    Mickéy    Mousé        71   m  12-18
51   1.0  56.0       70kgs    Mickéy    Mousé         -   f  00-06
68   1.0  56.0       70kgs    Mickéy    Mousé         -   f  06-12
85   1.0  56.0       70kgs    Mickéy    Mousé         -   f  12-18
1    2.0  34.0   154.89lbs    Donald     Duck         -   m  00-06
18   2.0  34.0   154.89lbs    Donald     Duck         -   m  06-12
35   2.0  34.0   154.89lbs    Donald     Duck         -   m  12-18
52   2.0  34.0   154.89lbs    Donald     Duck        85   f  00-06
69   2.0  34.0   154.89lbs    Donald     Duck        84   f  06-12
86   2.0  34.0   154.89lbs    Donald     Duck        76   f  12-18
4    5.0  54.0  198.658lbs      Pink  Panther         -   m  00-06
21   5.0  54.0  198.658lbs      Pink  Panther         -   m  06-12
38   5.0  54.0  198.658lbs      Pink  Panther         -   m  12-18
55   5.0  54.0  198.658lbs      Pink  Panther        69   f  00-06
89   5.0  54.0  198.658lbs      Pink  Panther        75   f  12-18
5    6.0  52.0      189lbs      Huey   McDuck         -   m  00-06
22   6.0  52.0      189lbs      Huey   McDuck         -   m  06-12
39   6.0  52.0      189lbs      Huey   McDuck         -   m  12-18
56   6.0  52.0      189lbs      Huey   McDuck        68   f  00-06
73   6.0  52.0      189lbs      Huey   McDuck        75   f  06-12
90   6.0  52.0      189lbs      Huey   McDuck        72   f  12-18
6    7.0  19.0       56kgs     Dewey   McDuck         -   m  00-06
23   7.0  19.0       56kgs     Dewey   McDuck         -   m  06-12
40   7.0  19.0       56kgs     Dewey   McDuck         -   m  12-18
57   7.0  19.0       56kgs     Dewey   McDuck        71   f  00-06
74   7.0  19.0       56kgs     Dewey   McDuck        78   f  06-12
91   7.0  19.0       56kgs     Dewey   McDuck        75   f  12-18
7    8.0  32.0       78kgs    Scööpy      Doo        78   m  00-06
24   8.0  32.0       78kgs    Scööpy      Doo        76   m  06-12
41   8.0  32.0       78kgs    Scööpy      Doo        75   m  12-18
58   8.0  32.0       78kgs    Scööpy      Doo         -   f  00-06
75   8.0  32.0       78kgs    Scööpy      Doo         -   f  06-12
92   8.0  32.0       78kgs    Scööpy      Doo         -   f  12-18
10   9.0  52.0      189lbs      Huey   McDuck         -   m  00-06
27   9.0  52.0      189lbs      Huey   McDuck         -   m  06-12
44   9.0  52.0      189lbs      Huey   McDuck         -   m  12-18
61   9.0  52.0      189lbs      Huey   McDuck        68   f  00-06
78   9.0  52.0      189lbs      Huey   McDuck        75   f  06-12
95   9.0  52.0      189lbs      Huey   McDuck        72   f  12-18
11  10.0  12.0       45kgs     Louie   McDuck         -   m  00-06
28  10.0  12.0       45kgs     Louie   McDuck         -   m  06-12
45  10.0  12.0       45kgs     Louie   McDuck         -   m  12-18
62  10.0  12.0       45kgs     Louie   McDuck        92   f  00-06
79  10.0  12.0       45kgs     Louie   McDuck        95   f  06-12
96  10.0  12.0       45kgs     Louie   McDuck        87   f  12-18